yarnPath: .yarn/releases/yarn-3.6.4.cjs

nodeLinker: node-modules

packageExtensions:
  '@slidev/cli@0.43.5':
    dependencies:
      '@types/markdown-it': '13.0.1'
      'postcss': '8.4.31'
  '@slidev/client@0.43.5':
    dependencies:
      'vite': '4.4.9'
  '@vueuse/core@10.4.1':
    dependencies:
      'vue': '3.3.4'
  '@vueuse/math@10.4.1':
    dependencies:
      'vue': '3.3.4'
  '@vueuse/shared@10.4.1':
    dependencies:
      'vue': '3.3.4'

